apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: default
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
        - containerPort: 14268
        - containerPort: 14250
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 55681
          name: otlp-http
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: default
spec:
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: ui
    - port: 14268
      targetPort: 14268
      protocol: TCP
      name: collector
    - port: 14250
      targetPort: 14250
      protocol: TCP
      name: query
    - port: 6831
      targetPort: 6831
      protocol: UDP
      name: agent-udp
    - port: 6832
      targetPort: 6832
      protocol: UDP
      name: agent-udp-sampling
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlp
    - port: 55681
      targetPort: 55681
      protocol: TCP
      name: otlp-http
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 16686
      protocol: TCP
      name: http
  selector:
    app: jaeger
