apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask-weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-flask-weather-app
  template:
    metadata:
      annotations: 
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        app: k8s-flask-weather-app
    spec:
      containers:
      - name: flask-app
        image: weather-app-test:v3
        ports:
        - containerPort: 5000
        env:
        - name: VAULT_ADDR
          value: http://vault:8200
---
apiVersion: v1
kind: Service
metadata:
  name: flask-weather-app-service
spec:
  selector:
    app: k8s-flask-weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort

